### ISSUE TITLE
Shipping py3-requiring code to py2.7

### ISSUE THREAD

**Issue by dwhswenson** [conda-forge/nose-feedstock#23]
Issue: New build includes some py3-only code, and is shipping to 2.7

```bash
conda create -n broken-nose -c conda-forge python=2.7 nose
conda activate broken-nose  # see what I did there? 😄 
python -c "import nose" 
```

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dwhs/miniconda3/envs/broken-nose/lib/python2.7/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/Users/dwhs/miniconda3/envs/broken-nose/lib/python2.7/site-packages/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/Users/dwhs/miniconda3/envs/broken-nose/lib/python2.7/site-packages/nose/config.py", line 6, in <module>
    import configparser
ImportError: No module named configparser
```

(also, that was odd, because I got a different one in my unit tests... so....)

```bash
conda install configparser
python -c "import nose"
```

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dwhs/miniconda3/envs/broken-nose/lib/python2.7/site-packages/nose/__init__.py", line 3, in <module>
    from nose.exc import SkipTest, DeprecatedTest
  File "/Users/dwhs/miniconda3/envs/broken-nose/lib/python2.7/site-packages/nose/exc.py", line 8, in <module>
    from nose.plugins.skip import SkipTest
  File "/Users/dwhs/miniconda3/envs/broken-nose/lib/python2.7/site-packages/nose/plugins/skip.py", line 9, in <module>
    from nose.plugins.errorclass import ErrorClass, ErrorClassPlugin
  File "/Users/dwhs/miniconda3/envs/broken-nose/lib/python2.7/site-packages/nose/plugins/errorclass.py", line 130
    class ErrorClassPlugin(Plugin, metaclass=MetaErrorClass):
                                            ^
SyntaxError: invalid syntax
```

(that's what I saw on Travis)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/dwhs/miniconda3/envs/broken-nose:
#
# Name                    Version                   Build  Channel
backports                 1.0                        py_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
configparser              3.7.3            py27h8c360ce_2    conda-forge
libcxx                    10.0.1               h5f48129_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
ncurses                   6.2                  hb1e8313_1    conda-forge
nose                      1.3.7           pyh9f0ad1d_1005    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
python                    2.7.15          h8e446fc_1011_cpython    conda-forge
python_abi                2.7                     1_cp27m    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
sqlite                    3.33.0               h960bd1c_1    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
zlib                      1.2.11            h7795811_1009    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : broken-nose
    active env location : /Users/dwhs/miniconda3/envs/broken-nose
            shell level : 3
       user config file : /Users/dwhs/.condarc
 populated config files : /Users/dwhs/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/dwhs/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/omnia/osx-64
                          https://conda.anaconda.org/omnia/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/dwhs/miniconda3/pkgs
                          /Users/dwhs/.conda/pkgs
       envs directories : /Users/dwhs/miniconda3/envs
                          /Users/dwhs/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

(but issue occurred on fresh miniconda on travis)
</details>

**Comment by jakirkham** [comment]
Maybe related to PR ( https://github.com/conda-forge/nose-feedstock/pull/22 )?

cc @mariusvniekerk

**Comment by dwhswenson** [comment]
Definitely related to #22 : this came to me from daily builds that passed yesterday, and nose hasn't updated since 2015.

Problem is that nose, is, apparently, not "noarch" on PyPI. You actually get different source if Py2 vs Py3.

I created environments to pip-install nose in py2 and py3 and then:

```bash
diff miniconda3/envs/pip-nose/lib/python3.9/site-packages/nose/plugins/errorclass.py \
     miniconda3/envs/pip-nose-py2/lib/python2.7/site-packages/nose/plugins/errorclass.py
```

```diff
45c45
<     ... 
---
>     ...
106c106
<         for name, detail in list(attr.items()):
---
>         for name, detail in attr.items():
130c130
< class ErrorClassPlugin(Plugin, metaclass=MetaErrorClass):
---
> class ErrorClassPlugin(Plugin):
134a135
>     __metaclass__ = MetaErrorClass
143c144
<         if [c for c in classes if issubclass(err_cls, c)]:
---
>         if filter(lambda c: issubclass(err_cls, c), classes):
210d210
< 
```

**Comment by jakirkham** [comment]
Ah looks like they are [using `2to3`]( https://github.com/nose-devs/nose/blob/7c26ad1e6b7d308cafa328ad34736d34028c122a/setup3lib.py#L4 ). Yeah I don't think we can make this `noarch: python` then. Could you please submit a PR to remove `noarch: python` here and submit a PR to mark the current package broken ( https://github.com/conda-forge/admin-requests#mark-packages-as-broken-on-conda-forge )?
