### ISSUE TITLE
Upload failure Travis CI Python 3.5

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/nose-feedstock#3]
Appears the Python 3.5 OS X package failed to upload. Have copied the snippet from the failure below. Have paste the log into this [gist](https://gist.github.com/jakirkham/cdb3ce6069b26f2d382b46f0304733b7). Am going to restart Travis CI to get this uploaded, which sadly will replace the log there.

See issue ( https://github.com/conda-forge/conda-smithy/issues/267 ) for ensuring failure on bad upload with Travis CI. See issue ( https://github.com/conda-forge/status/issues/4 ) for details on the general Anaconda upload issues experienced at conda-forge. See issue ( https://github.com/Anaconda-Platform/support/issues/60 ) for the outline of the problem experience when uploading to Anaconda.org.

```
$ ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "./ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "./ci_support/upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "./ci_support/upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/mixins/channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -> 404)', 404)
```

**Comment by jakirkham** [comment]
The restarted build did not encounter this issue. All packages now uploaded. Closing...
