### ISSUE TITLE
`setuptools` run requirement

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/nose-feedstock#4]
Looks like `nose` requires `setuptools` to run certain things.

> Like at the bottom of https://circleci.com/gh/conda-forge/staged-recipes/7668
> 
> ```
> + nosetests cycpp_tests.py
> Traceback (most recent call last):
>   File "/opt/conda/envs/_test/bin/nosetests", line 6, in <module>
>     sys.exit(nose.run_exit())
>   File "/opt/conda/envs/_test/lib/python3.5/site-packages/nose/core.py", line 121, in __init__
>     **extra_args)
>   File "/opt/conda/envs/_test/lib/python3.5/unittest/main.py", line 93, in __init__
>     self.parseArgs(argv)
>   File "/opt/conda/envs/_test/lib/python3.5/site-packages/nose/core.py", line 145, in parseArgs
>     self.config.configure(argv, doc=self.usage())
>   File "/opt/conda/envs/_test/lib/python3.5/site-packages/nose/config.py", line 281, in configure
>     options, args = self._parseArgs(argv, cfg_files)
>   File "/opt/conda/envs/_test/lib/python3.5/site-packages/nose/config.py", line 268, in _parseArgs
>     self.getParser(), self.configSection, file_error=warn_sometimes)
>   File "/opt/conda/envs/_test/lib/python3.5/site-packages/nose/config.py", line 590, in getParser
>     self.plugins.loadPlugins()
>   File "/opt/conda/envs/_test/lib/python3.5/site-packages/nose/plugins/manager.py", line 378, in loadPlugins
>     from pkg_resources import iter_entry_points
> ImportError: cannot import name 'iter_entry_points'
> ```

Borrowed from [gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=57bc4a3dcd00bdff6e71d6af).

cc @scopatz

**Comment by jakirkham** [comment]
Can confirm it is [importing `pkg_resources`](https://github.com/nose-devs/nose/blob/release_1.3.7/nose/plugins/manager.py#L378).
